/*
 * This file is generated by jOOQ.
 */
package com.jooqspringboot.jooqspringbootproject.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

    private static final long serialVersionUID = -156681470;

    private Integer   idauthor;
    private String    firstName;
    private String    lastName;
    private LocalDate dateOfBirth;
    private Byte      distinguished;

    public Author() {}

    public Author(Author value) {
        this.idauthor = value.idauthor;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.dateOfBirth = value.dateOfBirth;
        this.distinguished = value.distinguished;
    }

    public Author(
        Integer   idauthor,
        String    firstName,
        String    lastName,
        LocalDate dateOfBirth,
        Byte      distinguished
    ) {
        this.idauthor = idauthor;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.distinguished = distinguished;
    }

    public Integer getIdauthor() {
        return this.idauthor;
    }

    public void setIdauthor(Integer idauthor) {
        this.idauthor = idauthor;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Byte getDistinguished() {
        return this.distinguished;
    }

    public void setDistinguished(Byte distinguished) {
        this.distinguished = distinguished;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Author other = (Author) obj;
        if (idauthor == null) {
            if (other.idauthor != null)
                return false;
        }
        else if (!idauthor.equals(other.idauthor))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!firstName.equals(other.firstName))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!lastName.equals(other.lastName))
            return false;
        if (dateOfBirth == null) {
            if (other.dateOfBirth != null)
                return false;
        }
        else if (!dateOfBirth.equals(other.dateOfBirth))
            return false;
        if (distinguished == null) {
            if (other.distinguished != null)
                return false;
        }
        else if (!distinguished.equals(other.distinguished))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idauthor == null) ? 0 : this.idauthor.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.dateOfBirth == null) ? 0 : this.dateOfBirth.hashCode());
        result = prime * result + ((this.distinguished == null) ? 0 : this.distinguished.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(idauthor);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(distinguished);

        sb.append(")");
        return sb.toString();
    }
}
