/*
 * This file is generated by jOOQ.
 */
package com.jooqspringboot.jooqspringbootproject.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 724976478;

    private Integer idbook;
    private String  title;
    private String  publisherName;
    private String  publishDate;
    private String  language;

    public Book() {}

    public Book(Book value) {
        this.idbook = value.idbook;
        this.title = value.title;
        this.publisherName = value.publisherName;
        this.publishDate = value.publishDate;
        this.language = value.language;
    }

    public Book(
        Integer idbook,
        String  title,
        String  publisherName,
        String  publishDate,
        String  language
    ) {
        this.idbook = idbook;
        this.title = title;
        this.publisherName = publisherName;
        this.publishDate = publishDate;
        this.language = language;
    }

    public Integer getIdbook() {
        return this.idbook;
    }

    public void setIdbook(Integer idbook) {
        this.idbook = idbook;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPublisherName() {
        return this.publisherName;
    }

    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    public String getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Book other = (Book) obj;
        if (idbook == null) {
            if (other.idbook != null)
                return false;
        }
        else if (!idbook.equals(other.idbook))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (publisherName == null) {
            if (other.publisherName != null)
                return false;
        }
        else if (!publisherName.equals(other.publisherName))
            return false;
        if (publishDate == null) {
            if (other.publishDate != null)
                return false;
        }
        else if (!publishDate.equals(other.publishDate))
            return false;
        if (language == null) {
            if (other.language != null)
                return false;
        }
        else if (!language.equals(other.language))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idbook == null) ? 0 : this.idbook.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.publisherName == null) ? 0 : this.publisherName.hashCode());
        result = prime * result + ((this.publishDate == null) ? 0 : this.publishDate.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(idbook);
        sb.append(", ").append(title);
        sb.append(", ").append(publisherName);
        sb.append(", ").append(publishDate);
        sb.append(", ").append(language);

        sb.append(")");
        return sb.toString();
    }
}
